#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/03843c6f-6c39-492c-8669-02b95b8cf83e/ # 
title: CustomerAccounts
types:
  Customer: !include customertype.raml
/customers:
  get:
    queryParameters:
      accessPerGrade:
        required: false
        enum:
          - supervisor
          - senior associate
          - associate
      
    responses:
      200:
        body:
          application/json:
            type: Customer[]
            examples:
              output: !include customersdataexample.raml
  post:
    body:
      application/json:
        type: Customer
        examples:
          input: !include postrequestexample.raml
    responses:
      201:
        body:
          application/json:
            example:
              message : Congratulations!! Customer has been added.
              

  
