#%RAML 1.0 NamedExample
value:
  -
    ID: 1 
    firstname: Shubham
    lastname: Gupta
    age: 25
    gender : male
    phone: 8098780854
    email: shubhamgupta@gmail.com
    grade: associate
  - 
    ID: 2
    firstname: Sneha
    lastname: Gupta
    age: 28
    gender : female
    phone: 9999999999
    email: snehagpt@gmail.com
    grade: supervisor